spring:
  application:
    name: service01
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  rabbitmq:
    host: localhost
    port: 5672
    username: configserver
    password: configserver